### ISSUE TITLE
Image update

### ISSUE THREAD

**Issue by lsgroi** [WireMock-Net/WireMock.Net-docker#1]
The image on Docker Hub is still tagged preview, are you considering update to the latest version?

**Comment by StefH** [comment]
Good point.

I will update the docker image with latest version this weekend.

**Comment by lsgroi** [comment]
Thanks! I am running tests in-memory as well as out of process so this docker image turned out to be super useful.

**Comment by StefH** [comment]
Version 1.0.4.5 for linux and windows-nano has been added.
