### ISSUE TITLE
Persisting the recorded mappings 

### ISSUE THREAD

**Issue by zuekut** [WireMock-Net/WireMock.Net-docker#10]
Hello,

I was trying to figure out how to persist the recorded stub mappings to my local file system made in the docker container running the WireMock.Net server instance, in order to use them as static mappings for my unit tests. I tried by creating a volume for the docker instance, however, I wasn't able to successfully access them. Thanks in advance!

**Comment by StefH** [comment]
@zuekut Did you have any progress on this issue?

**Comment by StefH** [comment]
@zuekut, an example has been added to the Wiki : https://github.com/WireMock-Net/WireMock.Net-docker/wiki/Docker-Compose
