### ISSUE TITLE
Change: Disable partial match by default for StandAlone application.

### ISSUE THREAD

**Issue by DiamondDragon** [WireMock-Net/WireMock.Net-docker#3]
It took me some time to realize that Docker container has partial match enabled by default. Here is related line of code:

https://github.com/WireMock-Net/WireMock.Net/blob/4283732b6cd8d96dd5fde806495e80f5326b6759/src/WireMock.Net.StandAlone/StandAloneApp.cs#L49

It would be good if partial match was disabled by default. If it's enabled it very confusing when you get matches for requests which were not stubbed.

**Comment by StefH** [comment]
OK
If it helps, I can make the setting default to **false**.

I'll first create a new WireMock.Net release, after that I wait on your answer on https://github.com/WireMock-Net/WireMock.Net-docker/issues/4 and then I create a new docker.

**Comment by StefH** [comment]
Fixed in 1.0.4.18 (also docker is uploaded today)
