### ISSUE TITLE
Wrong Nanoserver Base Image

### ISSUE THREAD

**Issue by davidguidali** [WireMock-Net/WireMock.Net-docker#32]
You should use e.g. 
mcr.microsoft.com/dotnet/core/sdk:3.1-nanoserver-1809

instead of

mcr.microsoft.com/windows/nanoserver:1809

Otherwise you won't be able to execute the dotnet command. Nanoserver doesn't include dotnet per default anymore.

**Comment by StefH** [comment]
@davidguidali 

I fixed some images,
https://github.com/WireMock-Net/WireMock.Net-docker/pull/33


However 1803 remains a problem:
```
PS C:\Dev\GitHub\WireMock.Net-docker\StandAlone.NETCoreApp> docker run --rm -i -p 9090:80 sheyenrath/wiremock.net-nanoserver-1803 --AdminUsername a --AdminPassword b
It was not possible to find any compatible framework version
The framework 'Microsoft.AspNetCore.App', version '3.1.0' was not found.
  - The following frameworks were found:
      3.1.0-preview3.19555.2 at [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]

You can resolve the problem by installing the specified framework and/or SDK.
```

So maybe just remove support for this one?

**Comment by StefH** [comment]
https://github.com/WireMock-Net/WireMock.Net-docker/pull/33
