### ISSUE TITLE
Persist mappings?

### ISSUE THREAD

**Issue by mattisking** [WireMock-Net/WireMock.Net-docker#36]
How might I run the docker command(s) in such a way as to persist the mappings when I restart the container?

**Comment by mattisking** [comment]
Well, here's part of the way I think:
docker run -it --name wiremock-net -p 9091:80 -v $PWD/wiremock-net/mappings:/__admin/mappings sheyenrath/wiremock.net

At least, that gave me my named running instance with the necessary folder. Then:
docker cp .\bl-Default.json wiremock-net:/app/__admin/mappings/bl-Default.json

Restarted the container and my file is persisted.... but the application isn't loading it, which it does when I run the same sample locally?

**Comment by StefH** [comment]
@mattisking 
There is a wiki page that describes how to use docker compose:
https://github.com/WireMock-Net/WireMock.Net-docker/wiki/Docker-Compose

But if your solution also works, that's great! I'll also add that to the wiki.
