### ISSUE TITLE
Bug: Add "latest" table to docker image

### ISSUE THREAD

**Issue by DiamondDragon** [WireMock-Net/WireMock.Net-docker#4]
It would be good to add "latest" label to docker image to avoid the following error:

```
C:\Users\User>docker run -it --rm -p 9091:80 sheyenrath/wiremock.net-nano
Unable to find image 'sheyenrath/wiremock.net-nano:latest' locally
docker: Error response from daemon: manifest for sheyenrath/wiremock.net-nano:latest not found.
See 'docker run --help'.
```

**Comment by StefH** [comment]
You mean I also need to publish the `latest` docker to dockerhub?

Like `docker push sheyenrath/wiremock.net-nano:latest`?

Or just update the documentation to
`docker run -it --rm -p 9091:80 sheyenrath/wiremock.net-nano:1.0.4.13`

**Comment by StefH** [comment]
Version `1.0.4.13` is pushed as latest.
