### ISSUE TITLE
WireMock.Net Handlebars helper `Random` Fails in WireMock.Net.Testcontainers 1.6.6

### ISSUE THREAD

**Issue by Xor-el** [WireMock-Net/WireMock.Net-docker#51]
### Describe the bug
something seems to be broken in the WireMock.Net Handlebars `Random` helper (WireMock.Net.Testcontainers 1.6.4 was the last functional version for me).

### Expected behavior:
The HandleBar Random Helper should work as expected.

Expected Data Logged on Console

=================================Starting Tests=================================
Content Response = OK
Content Response Content = {"rate":168} // rate can be any random integer between 150 and 300

Actual Data Logged on Console

=================================Starting Tests=================================
Content Response = InternalServerError
Content Response Content = {"Status":"Template references a helper that cannot be resolved. Helper 'Random'"}

Test to reproduce

- 1 Clone [Repo](https://github.com/Xor-el/WireMock.NET-Random-Helper-Issue), and build.
- 2 Run the built demo. (Incase you get an error the first time you run the Demo, close it and run again.).

Other related info

Docker is needed to run the Demo as it uses WireMock.NET Test Container.

**Comment by StefH** [comment]
@Xor-el 
I've uploaded a fixed version for the Alpine image. All should work now.

**Comment by Xor-el** [comment]
Can confirm that this works as expected now.
Thanks @StefH for the quick turnaround.
